---

- name: "create destination directory"
  become: yes
  file: 
    path: /tmp/udapeople/
    state: directory

- name: "configuration play"
  become: yes
  unarchive:
    src: /../../../../backend/app.tar.gz
    dest: /tmp/udapeople/

- name: "Run backend"
  become: yes
  shell: |
    cd /tmp/udapeople/
    npm i
    pm2 start main.js