---

- name: "create destination directory"
  become: yes
  file: 
    path: /home/ubuntu/udapeople/
    state: directory

- name: "configuration play"
  become: yes
  unarchive:
    src: ../../backend/udapeople.backend
    dest: /home/ubuntu/udapeople/

- name: "Run backend"
  become: yes
  shell: |
    cd /home/ubuntu/udapeople/
    touch .env
    echo ENVIRONMENT=production > ".env"
    echo TYPEORM_CONNECTION=postgres >> ".env"
    echo TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js} >> ".env"
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
    echo NODE_ENV=production >> ".env"
    echo TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}" >> ".env"
    echo TYPEORM_PORT="{{ lookup('env', 'TYPEORM_PORT') }}" >> ".env"
    echo TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}" >> ".env"
    echo TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}" >> ".env"
    echo TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}" >> ".env"

- name: "Run backend"
  become: yes
  shell: |
    cd /home/ubuntu/udapeople/
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo pm2 start npm --no-automation --name "backend" -- run start